# Generated by Django 3.1.3 on 2020-12-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.CharField(max_length=350, verbose_name='Описание'),
        ),
    ]
