# Generated by Django 3.1.3 on 2020-12-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201209_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='costomer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
